### ISSUE TITLE
Problems with hidden list-items

### ISSUE THREAD

**Issue by RedEars** [352Media/flexMenu#14]
The Plugin doesn't seem to work when I have a li item hidden. 
My code is like this: 
```
<ul>
<li class="hidden">User-img</li>
<li>MenuItem 1</li>
<li>MenuItem 2</li>
<li>MenuItem 3</li>
</ul>
```

The result is that alle the items are wrapped in the dropdown and none (except the "More" Link) is shown.

**Comment by rdebeasi** [comment]
It might actually be that there's only space for two or fewer items outside the dropdown. In that case, flexMenu will put everything in the dropdown. You can disable this behavior by setting the "cutoff" variable to 0. Does that solve the problem?

**Comment by RedEars** [comment]
Thanks for your fast response, but it didn't resolve my problem. 
What I noticed is, that when I show the hidden LI Item with jquery.show(), two other Menu items show up (like it should be). 

Hidden LI State:
More

Visible LI State:
Visible Img | MenuItem1 | MenuItem2 | More => (MenuItem3 | MenuItem4 | MenuItem5)

It's correct on the visible state but not in the hidden state.

**Comment by RedEars** [comment]
I will try to make you a jsfiddle

**Comment by RedEars** [comment]
Here it is: 
http://jsfiddle.net/wn6h93jz/

For some reason, in the fiddle it doesnt even cutoff anything before the LI item is shown.

**Comment by rdebeasi** [comment]
Thanks for sending that example along! I'll take a closer look and get back to you.

**Comment by rdebeasi** [comment]
If a list item is hidden, flexMenu can't determine whether it will fit in the menu bar. I'd recommend moving the hidden image outside the `<ul>` element. It could be styled to look like part of the menu, even though it's a separate element.

I'm sorry for the delayed response!
