### ISSUE TITLE
dropdown not showing in Bootstrap 3

### ISSUE THREAD

**Issue by cvlug** [352Media/flexMenu#18]
In Bootstrap 3, the dropdowns are not showing.
It seems that the flexMenu-popup can not overrule the "overflow: hidden;" of .js .menu
tried about everything.
Somebody got a fix?

**Comment by rdebeasi** [comment]
Would you mind providing an example of this problem on JSFiddle or something similar? Thanks!

**Comment by rdebeasi** [comment]
It looks like Bootstrap is setting `position: relative;` on `.nav > li`, which is is messing with the flexMenu styles. If you override that and set `position: static;` instead, that should fix the problem. 

Sorry for the delayed response!
