### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by jasonbahl** [352Media/flexMenu#19]
There should be a callback once the items are folded into the menu. . .the layout I'm working with has some items fixed at the top of the page, and depending on the height of the menu, the content container gets a dynamic padding-height added to it to compensate. . .when the flexmenu runs I want to be able to re-process the height of the menu and dynamically update the padding height to match the new size of my flexmenu

If there was a callback, I could easily apply my function that sets the padding to the callback.

**Comment by rdebeasi** [comment]
That's a great idea - I'll definitely look into adding that feature.

If you're feeling inspired, I'm happy to accept pull requests! ;)

**Comment by Borovikov** [comment]
Сallback very need!

**Comment by rdebeasi** [comment]
Archiving this repo and closing all open issues. Thank you so much for your feedback - see you around the internet!! :slightly_smiling_face:
