### ISSUE TITLE
Target Option

### ISSUE THREAD

**Issue by Podders** [352Media/flexMenu#21]
I have an implementation where I have an existing left nav and a top nav driven by flexmenu, on smaller screens i'd love to be able to append the hidden nav items to a 'more' nav in my existing left nav, an option to define a target element to append the hidden nav items into instead of the default would be awesome,

**Comment by rdebeasi** [comment]
Could you please provide an example of how it's set up now and what you're looking for it to do? Thanks!

**Comment by Podders** [comment]
Sure, I did start to build this in in preparation for a pull request but it's still a little buggy at the moment,

The example below is kind of the setup I have running on a site i'm working on, the thinking is that we already have a 'Left' navigation so wanted to utilise that to hold the items that are removed from the top nav when the screen is too small,

Please take a look at [http://codepen.io/Podders/pen/JXXmje](http://codepen.io/Podders/pen/JXXmje) or [http://s.codepen.io/Podders/debug/JXXmje](http://s.codepen.io/Podders/debug/JXXmje)

Many thanks

**Comment by rdebeasi** [comment]
Awesome! That's a really cool feature. Once you have it working the way you want, I'd love to see a pull request! :)

**Comment by rdebeasi** [comment]
I'm going to close this issue, but if you'd like to provide a pull request and an example of how you're using this feature, I'd be happy to take a look! :)
