### ISSUE TITLE
Wrong version number in bower.json?

### ISSUE THREAD

**Issue by liayn** [352Media/flexMenu#22]
You tagged version 1.2 (as "1.2" whereas 1.1.1 has tag "v1.1.1" - incosistent), but bower.json still holds the version 1.1.1. Not correct, right?

**Comment by rdebeasi** [comment]
You're totally right on both fronts. I forgot to update bower.json with the new version. I'll update this issue when that's fixed.

Dropping "v" from the tag name was an intentional change, and I'm planning to stick with that style in the future.

Thanks for the heads-up! :smile:

**Comment by liayn** [comment]
Perfect. Thanks.
