### ISSUE TITLE
Add to npm

### ISSUE THREAD

**Issue by MrChe** [352Media/flexMenu#23]
Please add to npm!!!

**Comment by jameelmoses** [comment]
+ 100

**Comment by jameelmoses** [comment]
#39 made a PR for you

**Comment by jameelmoses** [comment]
@MrChe until this has been merged in, you can `yarn add 352Media/flexMenu#39/head -D`

**Comment by brianpaulrue** [comment]
Can we please get this PR merged in?

**Comment by rdebeasi** [comment]
This PR was merged in January 2018 - closing!

**Comment by rdebeasi** [comment]
Also, published :) https://www.npmjs.com/package/@rdebeasi/flexmenu
