### ISSUE TITLE
The last two menu items are hidden, but they are placed on the same line.

### ISSUE THREAD

**Issue by Boarworm** [352Media/flexMenu#25]
When I open the site the last two items on the menu are hidden (moved to the li tag with the class .flexMenu-viewMore). Although the menu fit on one line.

When I click "reload the page" in the browser, the menu is fully displayed in one line (as it should be).

When I change the width of the browser window the last two menu items are hidden, but should only hide the last menu item.

Here's a site where I do the menu: http://kupit-cheki.org
Please see this problem.

**Comment by rdebeasi** [comment]
I can reproduce this problem on your site, and I can actually see it on the demo page as well. I'll look into this issue and update this ticket with more details.

Thanks for the heads-up!

**Comment by rdebeasi** [comment]
This is resolved in flexMenu 1.4.2. Thanks again for the bug report!
