### ISSUE TITLE
Selfclosing menu in mobile google chrome on scroll

### ISSUE THREAD

**Issue by Storky** [352Media/flexMenu#33]
Cheers man, I like to use your menu.
Honestly I have not own smartphone, my friend with 4.5' android smartphone with chrome browser told me about this issue:

1. When expanded mobile menu is high , you gonna scroll down y-axis to see bottom list items of menu.
2. In mobile chrome on scroll bottom redundant address panel is sliding up, this way Window is resizing about Y-axis.
3. Flexmenu selfclosing on any 'resize' event, so User cant check bottom menu items with scroll, if its under bottom edge of the screen.

I solved this problem by adding resize handler, which is not working on y-axis resize.
Sorry for not good english.

```
        function ResizeHandler() {
		var windowW = $(window).width();
		return function () {
			if(windowW != $(window).width()){
				adjustFlexMenu();
				windowW = $(window).width();
			}
		}
	}

	var resizeHandler = ResizeHandler();
	$(window).resize(function () {

		clearTimeout(resizeTimeout);
		resizeTimeout = setTimeout(function () {
			resizeHandler();
			// adjustFlexMenu();
		}, 200);
	});
	/*$(window).resize(function () {
		clearTimeout(resizeTimeout);
		resizeTimeout = setTimeout(function () {
			adjustFlexMenu();
		}, 200);
	});*/
```

**Comment by rdebeasi** [comment]
Thanks for the heads-up! Are you using flexMenu 1.4 or later? This issue sounds like #15, which was fixed in that release.

**Comment by Storky** [comment]
You right, I used jQuery.flexMenu 1.3 , overlooked new release, will try new one today, thanks)
