### ISSUE TITLE
Popup menu sometimes closes when it shouldn't (in mobile browsers)

### ISSUE THREAD

**Issue by peedikuubik** [352Media/flexMenu#34]
When swiped up or down to scroll through menu items, the flexMenu popup sometimes closes instead. Needless to say, this is unwanted behaviour and bad UX.
I guess this has something to do with viewport height (whenever viewport size changes, the popup menu closes?).
For example, in Chrome and Firefox (for Android), the browser address bar is shown when you swipe up and hidden when you swipe down. Whenever that happens, the flexMenu popup closes.
This also happens on the flexMenu demo page (http://352media.github.io/flexMenu/).
Here's a video demonstrating this:
https://www.dropbox.com/s/2ppiqitbu26tilg/flexmenuswipebug.mp4?dl=0

**Comment by peedikuubik** [comment]
I forgot to say hello and thanks for the otherwise handy plugin. (:

**Comment by rdebeasi** [comment]
Thanks for letting me know about this!This bug sounds like #15, which was fixed in flexMenu 1.4. Does updating to the latest version resolve the problem?On Feb 8, 2017 4:33 PM, peedikuubik <notifications@github.com> wrote:I forgot to say hello and thanks for the otherwise handy plugin. (:

**Comment by peedikuubik** [comment]
Thanks for answering quickly.
I'm already using the latest plugin version (1.4.2).
As the video demonstrates (https://goo.gl/Fl1Yp4), the plugin demo page (using the latest plugin version) also has this issue.

**Comment by rdebeasi** [comment]
Got it. I can reproduce the issue. I'll take a closer look.

**Comment by peedikuubik** [comment]
Hi, rdebeasi,
just remembered this issue. Have you had time to look into this?

**Comment by rdebeasi** [comment]
I haven't had a chance to look into this yet. Sorry for the delay!

I maintain this project in my spare time, and spare time has been in short supply for me lately. In the meantime, if you'd like to take a crack at a fix, I happily accept pull requests! :smile:

**Comment by rdebeasi** [comment]
Archiving this repo and closing all open issues. Thank you so much for your feedback - see you around the internet!! :slightly_smiling_face:
