### ISSUE TITLE
Modal bootstrap appear behind the menu

### ISSUE THREAD

**Issue by MarokoSakura** [352Media/flexMenu#35]
Hi, 
im using flexmenu : when I click on an item that displays a modal, the modal appear behind the menu.
is thier any paraetre to add to my code  
`// Flex Menu

		$('.menu').flexMenu({
			breakpoint: 3000,
			responsivePattern: 'off-canvas',
			animationSpeed: 300
		});

		$(".fm-button").click(function(){
			if($("header").css('right') == '0px'){
				$("header").stop().animate({right:'240px'},300);
			};
			if($("header").css('right') == '240px'){
				$("header").stop().animate({right:'0px'},300);
			};
		 });`

**Comment by rdebeasi** [comment]
It sounds like you may need to adjust the `z-index` value for `.flexMenu-popup` in your CSS.

Also, the plugin in this repo doesn't have any of the options that you used in your code (`breakpoint`, `responsivePattern`, and `animationSpeed`). Is it possible that you're confusing the 352Media flexMenu plugin with [this flexMenu plugin](http://avirtum.com/demo/flexmenu/)?

**Comment by MarokoSakura** [comment]
Hi, 
thanks for your reply, and sorry for the misunderstanding. The plugin came with the template and i didn't figure out witch was the right plugin.
thanks for your help

**Comment by rdebeasi** [comment]
No worries at all!
