### ISSUE TITLE
I found a bug

### ISSUE THREAD

**Issue by ekkky** [352Media/flexMenu#37]
Hello!
I found a bug.
I turned off the style overflow="hidden" to better be seen.
Watch the video: https://drive.google.com/open?id=0B57RPXJWXRAjVHZsT1ZKdFlKOEE
How to fix it? Really need = (((

**Comment by rdebeasi** [comment]
The link is broken, and it's not clear what's being described here. I'm closing this issue, but feel free to open a new issue with more details!
