### ISSUE TITLE
getting "Cannot read property 'flexMenu' of null"

### ISSUE THREAD

**Issue by gt06** [352Media/flexMenu#38]
hey i have integrated your plugin code in my project. also i have loaded jquey version-3.1.1 before loading flexmenu.js. i am getting can not read property of "flexmenu" of null.

**Comment by rdebeasi** [comment]
Without seeing the code that triggered this issue, my best guess is that jQuery didn't find the element that you were looking for and returned you `null` instead. Calling flexMenu on null would trigger the error that you described.

This doesn't sound like an issue with flexMenu - closing.
