### ISSUE TITLE
Vertical menu

### ISSUE THREAD

**Issue by harsshkishore** [352Media/flexMenu#40]
Can we have the same code working for Vertical menu(stacked), Right now this works for horizontal menu.

**Comment by rdebeasi** [comment]
I'm not currently working on this feature, but if you'd like to submit a pull request, I'd be happy to take a look! 🙂

**Comment by rdebeasi** [comment]
Archiving this repo and closing all open issues. Thank you so much for your feedback - see you around the internet!! :slightly_smiling_face:
