### ISSUE TITLE
Flexmenu breaks when open links in new tab and coming back to the site

### ISSUE THREAD

**Issue by Magudeeswaran9191** [352Media/flexMenu#44]
Hi,
In touch device when i clicked a menu item which opens in new tab, and then after coming back to the site the menu item which i clicked goes under the more + menu.
For example:
Menu 1
	submenu 1 ( external link )
	submenu 2 ( external link )
	submenu 3 ( external link )
Menu 2
.
.
.
More +
	Sublinks of more menu	
When i click the submenu 1 and then link open in new tab then i will close the tab and come back to the site the menu order changes likes this.
Menu 1
Menu 2
.
.
.
More +
	submenu 1 ( external link )
	submenu 2 ( external link )
	submenu 3 ( external link )
	Sublinks of more menu	
No idea why this is happening. Kindly please advise.

Thanks,
Magu

**Comment by rdebeasi** [comment]
Hi! Thanks for sharing that report. Could you please provide an example of a page where this is happening?

**Comment by Magudeeswaran9191** [comment]
Hi,

This is a intranet application and you can not access outside, also i cant share the screenshot as well.

Thats why i explained with example.

Thanks for the understanding.

**Comment by rdebeasi** [comment]
Hi! I'm unfortunately not able to help troubleshoot this without a test case. Sorry I can't be more helpful!
