### ISSUE TITLE
Multiple flexMenu?

### ISSUE THREAD

**Issue by nkforeg** [352Media/flexMenu#45]
How can i use multiple flexMenu in same page?
Ex: menu1 shouldApply for all screen size and menu2 shouldApply if screen min-width 768px.
Thanks!

**Comment by rdebeasi** [comment]
You could include a function to check the viewport width when initializing flexMenu:

```js
$('ul.menu1.flex').flexMenu({
    shouldApply: function() { return ( $( window ).width() >= 768 ); }
});
```

**Comment by nkforeg** [comment]
Thank you so much!

**Comment by rdebeasi** [comment]
Sure thing - glad I could help! :smile:
