### ISSUE TITLE
Build Awesome New Demo Page

### ISSUE THREAD

**Issue by rdebeasi** [352Media/flexMenu#6]
Build an awesome new demo page to replace current one. Include a few different examples of what FlexMenu does and how people might use the various options in creative ways. CSS3 snazziness would also be great. Make it pop! ;)

**Comment by mylastore** [comment]
Close to what I been looking for. What I have in mind is when the last item on the menu runs out of window space convert the entire menu to a dropdown. I have the CSS in place just need to add or remove a class to the ul element.  Can someone tell me how can I modify this library to do that?

**Comment by rdebeasi** [comment]
Setting the `cutoff` option to a really high number - say, 99 - would probably do the trick.

That said, this issue is actually about building a demo page, not tweaking the library's behavior. 😄

**Comment by rdebeasi** [comment]
Archiving this repo and closing all open issues.
