### ISSUE TITLE
Close menu when something other than the menu is clicked

### ISSUE THREAD

**Issue by rdebeasi** [352Media/flexMenu#9]
When something other than the flexMenu is clicked (e.g., when the background is clicked), close the flexMenu.

**Comment by gtimur7** [comment]
I've added this:
```javascript
$moreLink.on("blur", function(){
    setTimeout(function(){
        $moreItem.removeClass('active');
        $popup.hide();
    }, 250);
} );
```

**Comment by rdebeasi** [comment]
Thank you! I'll use that as a starting point and see if I can work that into the plugin.

What's the reason for the timeout? Maybe I'm missing something, but I'd expect the menu to be hidden immediately.

**Comment by mbelair** [comment]
The solution above wasn't working for me, so I came up with this. Hope it can help someone else!

```
$(document).click(function(e) {
if ($(e.target).closest('.flexMenu-viewMore').length === 0) {
		$moreItem.removeClass('active');
		$popup.hide();
	}
});
```

**Comment by rdebeasi** [comment]
Archiving this repo and closing all open issues. Thank you so much for your feedback - see you around the internet!! :slightly_smiling_face:
